using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RPGCreationKit;
using RPGCreationKit.CellsSystem;
using UnityEditor;
using UnityEngine.AI;
using UnityEditor.SceneManagement;

namespace RPGCreationKit.CellsSystem
{
    /// <summary>
    /// This represent a NavMeshLink automatically generated by the RPG Creation Kit
    /// </summary>
    class CellConnection
    {
        public Cell cell;
        public Cell connectedTo;

        public CellConnection(Cell one, Cell two)
        {
            cell = one;
            connectedTo = two;
        }
    }

    [CustomEditor(typeof(Worldspace))]
    public class WorldspaceInspector : Editor
    {
        Worldspace refObj;

        private int linkWidthOffset = 2;

        void OnEnable()
        {
            refObj = (Worldspace)target;
        }

        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();

            EditorGUILayout.Space(15);

            EditorGUILayout.LabelField("Automated Actions:", EditorStyles.boldLabel);
            EditorGUILayout.BeginHorizontal("box");

            if (GUILayout.Button(new GUIContent("Generate all NavMeshes", "Rebuilds all NavMeshes of all the cells in this Worldspace")))
                GenerateAllNavMeshes();

            if (GUILayout.Button(new GUIContent("Generate NavMesh Links", "Generates all NavMeshLinks of all the cells in this Worldspace")))
                GenerateNavMeshLinks();

            EditorGUILayout.EndHorizontal();

            EditorGUILayout.BeginHorizontal("box");

            if (GUILayout.Button(new GUIContent("Update all cells", "Updates all the Cells")))
            {
                refObj.CalculateCellsCoordinates();
                refObj.CalculateCellsNeighboring();
                UpdateAllCells();
            }

            if (GUILayout.Button(new GUIContent("Bake All Scenes", "Bakes the lighting in every scene.")))
                BakeAllScenes();

            if (GUILayout.Button(new GUIContent("Bake All Scenes [ToD]", "Bakes the lighting in every scene using ToD.")))
                BakeAllScenesToD();

            EditorGUILayout.EndHorizontal();

            EditorGUILayout.BeginHorizontal("box");

            if (GUILayout.Button(new GUIContent("Regenerate all Items GUIDs", "Rebuilds GUIDs of every item points.")))
            {
                RegenerateItemsGUIDs();
            }

            EditorGUILayout.EndHorizontal();

        }

        /// <summary>
        /// Rebuilds all NavMeshes of all the cells in this Worldspace
        /// </summary>
        private void GenerateAllNavMeshes()
        {
            bool yes = EditorUtility.DisplayDialog("Confirm Generate all NavMeshes", "Are you sure you want to rebuild all NavMeshes of the Worldspace " + refObj.worldSpaceID + "? This can take a while especially on Worldspaces with a lot of cells.", "Yes", "No");

            if (!yes)
                return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            RPGCreationKitEditor.StopEditorWorldStreaming();

            refObj.CalculateCellsCoordinates();
            // Open scenes
            for (int i = 0; i < refObj.cells.Length; i++)
            {
                GameObject navmesh;

                EditorUtility.DisplayProgressBar("Generating NavMeshes...", "Working on " + refObj.cells[i].sceneRef.SceneName, ((float)i) / (float)refObj.cells.Length);

                Debug.Log(refObj.cells[i].sceneRef.SceneName);
                EditorSceneManager.OpenScene(refObj.cells[i].sceneRef.ScenePath, OpenSceneMode.Single);

                NavMeshSurface navmeshSur;

                // Check if the NavMesh Surface exists in the scene or not
                if (GameObject.Find("NavMesh") != null)
                {
                    navmeshSur = GameObject.Find("NavMesh").GetComponent<NavMeshSurface>();

                    if(navmeshSur == null)
                    {
                        Destroy(GameObject.Find("NavMesh"));

                        navmesh = new GameObject();
                        navmesh.transform.position = refObj.cells[i].cellInWorldCoordinates;
                        navmeshSur = navmesh.AddComponent<NavMeshSurface>();
                        navmesh.name = "NavMesh";
                    }
                }
                else
                {
                    navmesh = new GameObject();
                    navmesh.transform.position = refObj.cells[i].cellInWorldCoordinates;
                    navmeshSur = navmesh.AddComponent<NavMeshSurface>();
                    navmesh.name = "NavMesh";
                }

                navmeshSur.BuildNavMesh();

                EditorSceneManager.MarkAllScenesDirty();
                EditorSceneManager.SaveOpenScenes();
            }

            EditorUtility.ClearProgressBar();
        }

        // Tracks current connected cells, to avoid making duplicated Links
        List<CellConnection> connectedCells = new List<CellConnection>();
        public GameObject navmeshlinkprefab;
        /// <summary>
        /// Generates all NavMeshLinks of all the cells in this Worldspace
        /// </summary>
        private void GenerateNavMeshLinks()
        {
            bool yes = EditorUtility.DisplayDialog("Confirm Generate all NavMeshLinks", "Are you sure you want to generate all NavMesheLinks of the Worldspace " + refObj.worldSpaceID + "? This can take a while especially on Worldspaces with a lot of cells.", "Yes", "No");

            if (!yes)
                return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            RPGCreationKitEditor.StopEditorWorldStreaming();

            connectedCells = new List<CellConnection>();


            for (int i = 0; i < refObj.cells.Length; i++)
            {
                Cell curCell = refObj.cells[i];
                EditorUtility.DisplayProgressBar("Generating NavMeshLinks...", "Working on " + curCell.sceneRef.SceneName, ((float)i) / (float)refObj.cells.Length);

                var scene = EditorSceneManager.OpenScene(curCell.sceneRef.ScenePath, OpenSceneMode.Single);
                EditorSceneManager.SetActiveScene(scene);

                // Find the NavMeshLink Holder
                GameObject navMeshLinkHolder = GameObject.Find("NavMeshLinks");
                if (navMeshLinkHolder == null)
                    navMeshLinkHolder = new GameObject("NavMeshLinks");

                navMeshLinkHolder.transform.position = new Vector3(curCell.cellInWorldCoordinates.x, curCell.cellInWorldCoordinates.y, curCell.cellInWorldCoordinates.z);

                // Clear the NavMeshLinksHolder
                for (int j = navMeshLinkHolder.transform.childCount - 1; j >= 0; j--)
                    DestroyImmediate(navMeshLinkHolder.transform.GetChild(j).gameObject);

                // Look at the cell where we need to make a link
                Cell[] topRightDownLeft = new Cell[4]; // 0 top - 1 right - 2 down - 3 left

                topRightDownLeft[0] = curCell.neighboringCells[1]; // top
                topRightDownLeft[1] = curCell.neighboringCells[3]; // right
                topRightDownLeft[2] = curCell.neighboringCells[5]; // down
                topRightDownLeft[3] = curCell.neighboringCells[7]; // left


                if (topRightDownLeft[0] != null)
                {
                    // Do links
                    if (!AreConnected(curCell, topRightDownLeft[0]))
                    {

                        GameObject newLink = Instantiate(navmeshlinkprefab);
                        newLink.name = "NavMeshLink (N)";


                        // Set position
                        newLink.transform.position = new Vector3(curCell.cellInWorldCoordinates.x, 0, curCell.cellInWorldCoordinates.z + ((refObj.cellSize.y) / 2));

                        // Set Rotation

                        Connect(curCell, topRightDownLeft[0]);

                        newLink.transform.parent = navMeshLinkHolder.transform;
                    }
                }

                if (topRightDownLeft[1] != null)
                {
                    // Do links
                    if (!AreConnected(curCell, topRightDownLeft[1]))
                    {
                        GameObject newLink = Instantiate(navmeshlinkprefab);
                        newLink.name = "NavMeshLink (E)";

                        // Set position
                        newLink.transform.position = new Vector3(curCell.cellInWorldCoordinates.x + ((refObj.cellSize.x) / 2), 0, curCell.cellInWorldCoordinates.z);

                        // Set Rotation
                        newLink.transform.eulerAngles = new Vector3(0, 90, 0);

                        Connect(curCell, topRightDownLeft[1]);

                        newLink.transform.parent = navMeshLinkHolder.transform;
                    }
                }

                if (topRightDownLeft[2] != null)
                {
                    // Do links
                    if (!AreConnected(curCell, topRightDownLeft[2]))
                    {
                        GameObject newLink = Instantiate(navmeshlinkprefab);
                        newLink.name = "NavMeshLink (S)";

                        // Set position
                        newLink.transform.position = new Vector3(curCell.cellInWorldCoordinates.x, 0, curCell.cellInWorldCoordinates.z - ((refObj.cellSize.y) / 2));

                        // Set Rotation

                        Connect(curCell, topRightDownLeft[2]);

                        newLink.transform.parent = navMeshLinkHolder.transform;
                    }
                }

                if (topRightDownLeft[3] != null)
                {
                    // Do links
                    if (!AreConnected(curCell, topRightDownLeft[3]))
                    {
                        GameObject newLink = Instantiate(navmeshlinkprefab);
                        newLink.name = "NavMeshLink (W)";

                        // Set position
                        newLink.transform.position = new Vector3(curCell.cellInWorldCoordinates.x - ((refObj.cellSize.x) / 2), 0, curCell.cellInWorldCoordinates.z);

                        // Set Rotation
                        newLink.transform.eulerAngles = new Vector3(0, 90, 0);

                        Connect(curCell, topRightDownLeft[3]);

                        newLink.transform.parent = navMeshLinkHolder.transform;
                    }
                }

                EditorSceneManager.MarkAllScenesDirty();
                EditorSceneManager.SaveOpenScenes();
            }

            EditorUtility.ClearProgressBar();
        }


        private void BakeAllScenes()
        {
            bool yes = EditorUtility.DisplayDialog("Confirm Bake All Scenes", "Are you sure you want to bake all Scenes of the Worldspace " + refObj.worldSpaceID + "? This can take several hours especially on Worldspaces with a lot of cells.", "Yes", "No");

            if (!yes)
                return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            RPGCreationKitEditor.StopEditorWorldStreaming();

            // Open scenes
            for (int i = 0; i < refObj.cells.Length; i++)
            {
                EditorUtility.DisplayProgressBar("Baking scenes...", "Working on " + refObj.cells[i].sceneRef.SceneName, ((float)i) / (float)refObj.cells.Length);

                Debug.Log(refObj.cells[i].sceneRef.SceneName);
                EditorSceneManager.OpenScene(refObj.cells[i].sceneRef.ScenePath, OpenSceneMode.Single);

                Lightmapping.Bake();

                EditorSceneManager.MarkAllScenesDirty();
                EditorSceneManager.SaveOpenScenes();
            }

            EditorUtility.ClearProgressBar();
        }

        private void BakeAllScenesToD()
        {
            bool yes = EditorUtility.DisplayDialog("Confirm Bake All Scenes ToD", "Are you sure you want to bake all Scenes ToD of the Worldspace " + refObj.worldSpaceID + "? This can take several hours especially on Worldspaces with a lot of cells.", "Yes", "No");

            if (!yes)
                return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            RPGCreationKitEditor.StopEditorWorldStreaming();

            // Open scenes
            for (int i = 0; i < refObj.cells.Length; i++)
            {
                EditorUtility.DisplayProgressBar("Baking scenes...", "Working on " + refObj.cells[i].sceneRef.SceneName, ((float)i) / (float)refObj.cells.Length);

                Debug.Log(refObj.cells[i].sceneRef.SceneName);
                EditorSceneManager.OpenScene(refObj.cells[i].sceneRef.ScenePath, OpenSceneMode.Single);

                RenderSettings.skybox = refObj.SkyboxMaterial;
                //Lightmapping.lightingDataAsset = refObj.lightingDataAsset;

                Lightmapping.Bake();

                EditorSceneManager.MarkAllScenesDirty();
                EditorSceneManager.SaveOpenScenes();
            }

            EditorUtility.ClearProgressBar();
        }

        private void UpdateAllCells()
        {
            bool yes = EditorUtility.DisplayDialog("Confirm Update All Cells", "Are you sure you want to Update every Cell of the Worldspace " + refObj.worldSpaceID + "? This can take a while especially on Worldspaces with a lot of cells.", "Yes", "No");

            if (!yes)
                return;

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            RPGCreationKitEditor.StopEditorWorldStreaming();

            // Open scenes
            for (int i = 0; i < refObj.cells.Length; i++)
            {
                EditorUtility.DisplayProgressBar("Updating cells...", "Working on " + refObj.cells[i].sceneRef.SceneName, ((float)i) / (float)refObj.cells.Length);

                try
                {

                    Debug.Log(refObj.cells[i].sceneRef.SceneName);
                    EditorSceneManager.OpenScene(refObj.cells[i].sceneRef.ScenePath, OpenSceneMode.Single);

                    // Get CellInfo
                    CellInformation cellInfo = FindObjectOfType<CellInformation>();
                    cellInfo.UpdateCellFromInspector();
                }
                catch
                {

                }

                EditorSceneManager.MarkAllScenesDirty();
                EditorSceneManager.SaveOpenScenes();
            }

            EditorUtility.ClearProgressBar();
        }

        private void RegenerateItemsGUIDs()
        {
            bool yes = EditorUtility.DisplayDialog("Confirm Regenerate Items GIUDs", "Are you sure you want to Regenerate every Item GIUD of the Worldspace " + refObj.worldSpaceID + "? This can take a while especially on Worldspaces with a lot of cells and lots of items.\n\nWARNING! If you have references in Scripts or anywhere else, this may break them. If so, make sure to update them afterwards.", "Yes", "No");

            if (!yes)
                return;


            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            RPGCreationKitEditor.StopEditorWorldStreaming();

            // Open scenes
            for (int i = 0; i < refObj.cells.Length; i++)
            {
                EditorUtility.DisplayProgressBar("Regenerating Items GUIDs...", "Working on " + refObj.cells[i].sceneRef.SceneName, ((float)i) / (float)refObj.cells.Length);

                Debug.Log(refObj.cells[i].sceneRef.SceneName);
                try
                {
                    EditorSceneManager.OpenScene(refObj.cells[i].sceneRef.ScenePath, OpenSceneMode.Single);

                    // Get CellInfo
                    ItemInWorld[] allItemsInWorld = FindObjectsOfType<ItemInWorld>();

                    for (int j = 0; j < allItemsInWorld.Length; j++)
                    {
                        allItemsInWorld[j].RegenerateGUIDStr();
                    }
                }
                catch { }


                EditorSceneManager.MarkAllScenesDirty();
                EditorSceneManager.SaveOpenScenes();
            }

            EditorUtility.ClearProgressBar();
        }


        /// <summary>
        /// Checks whether two cells are connected
        /// </summary>
        private bool AreConnected(Cell one, Cell two)
        {
            for (int i = 0; i < connectedCells.Count; i++)
            {
                if (connectedCells[i].cell.ID == one.ID && connectedCells[i].connectedTo.ID == two.ID ||
                    connectedCells[i].cell.ID == two.ID && connectedCells[i].connectedTo.ID == one.ID)
                    return true;
            }

            return false;
        }

        /// <summary>
        /// Adds a Link to the ConnectedCells tracker
        /// </summary>
        /// <param name="one"></param>
        /// <param name="two"></param>
        private void Connect(Cell one, Cell two)
        {
            connectedCells.Add(new CellConnection(one, two));
        }

    }
}